name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../admin-panel && npm ci
        cd ../microservices/event-service && npm ci
        cd ../reservation-service && npm ci
        cd ../payment-service && npm ci
        cd ../mail-service && npm ci
        cd ../shared && npm ci
    
    - name: Run linting
      run: |
        cd frontend && npm run lint
        cd ../microservices/event-service && npm run lint || true
        cd ../reservation-service && npm run lint || true
        cd ../payment-service && npm run lint || true
        cd ../mail-service && npm run lint || true
    
    - name: Run type checking
      run: |
        cd frontend && npm run type-check || npx tsc --noEmit
        cd ../microservices/event-service && npx tsc --noEmit
        cd ../reservation-service && npx tsc --noEmit
        cd ../payment-service && npx tsc --noEmit
        cd ../mail-service && npx tsc --noEmit
    
    - name: Run tests
      run: |
        cd microservices/event-service && npm test || true
        cd ../reservation-service && npm test || true
        cd ../payment-service && npm test || true
        cd ../mail-service && npm test || true
    
    - name: Build shared package
      run: |
        cd shared && npm run build
    
    - name: Build microservices
      run: |
        cd microservices/event-service && npm run build
        cd ../reservation-service && npm run build
        cd ../payment-service && npm run build
        cd ../mail-service && npm run build
    
    - name: Build frontend
      run: |
        cd frontend && npm run build
    
    - name: Build admin panel
      run: |
        cd admin-panel && npm run build

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=high
      continue-on-error: true
    
    - name: Run npm audit fix
      run: npm audit fix
      continue-on-error: true
